release scripts
Signed-off-by: Kwpolska <kwpolska@gmail.com>

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,6 +1,6 @@
 #!/bin/zsh
-project="aurqt"
-projectc="aurqt"
+project="tEmplate"
+projectc="TEMPLATE"
 
 version=$1
 if [[ $version = '' ]]; then
@@ -19,6 +19,7 @@ sed "s/version=.*/version='$version',/g" setup.py -i
 sed "s/release = .*/release = '$version'/g" docs/conf.py -i
 sed "s/:Version: .*/:Version: $version/g" docs/*.rst -i
 sed "s/# $projectc v.*/# $projectc v$version/" $project/*.py -i
+sed "s/# $projectc v.*/# $projectc v$version/" $project/ui/*.py -i
 sed "s/__version__ = .*/__version__ = '$version'/g" $project/__init__.py -i
 sed "s/pkgver=.*/pkgver=$version/g" PKGBUILD -i
 sed "s/pkgver=.*/pkgver=$datep/g" PKGBUILD-git -i
@@ -32,72 +33,72 @@ cp docs/README.rst docs/CHANGELOG.rst docs/CONTRIBUTING.rst .
 cp docs/README.rst README
 
 ###: Locale Generation
-xgettext -c ./$project/*.py ./$project/ui/*.py -o ./messages.pot
-
-sed '1,+17d' ./messages.pot > ./messages.pot.tmp
-
-pot='# '$projectc' pot file.
-# Copyright © 2012-2013, Kwpolska.
-# This file is distributed under the same license as the '$projectc' package.
-# Kwpolska <kwpolska@kwpolska.tk>, 2012-2013.
+#xgettext -c ./$project/*.py -o ./messages.pot
 #
-msgid ""
-msgstr ""
-"Project-Id-Version: #version\\n"
-"Report-Msgid-Bugs-To: Kwpolska <kwpolska@kwpolska.tk>\\n"
-"POT-Creation-Date: #datel\\n"
-"PO-Revision-Date: #datel\\n"
-"Last-Translator: Kwpolska <kwpolska@kwpolska.tk>\\n"
-"Language-Team: Kwpolska <kwpolska@kwpolska.tk>\\n"
-"Language: en\\n"
-"MIME-Version: 1.0\\n"
-"Content-Type: text/plain; charset=UTF-8\\n"
-"Content-Transfer-Encoding: 8bit\\n"'
-
-echo $pot > messages.pot
-cat ./messages.pot.tmp >> messages.pot
-rm ./messages.pot.tmp
-
-sed "s/#version/$version/g" messages.pot -i
-sed "s/#datel/$datel/g" messages.pot -i
-
-for i in ./locale/*; do
-    language=$(basename $i)
-
-    podir="./locale/$language/LC_MESSAGES"
-    popath="./locale/$language/LC_MESSAGES/$project.po"
-    sed 's/\"Project-Id-Version: .*/\"Project-Id-Version: '$version'\\n\"/' $popath -i
-    msgmerge $popath messages.pot -o $popath
-    fuzzy=$(cat $popath | grep -c '#, fuzzy')
-    empty=$(cat $popath | pcregrep -cM 'msgstr ""\n$')
-    if [ $fuzzy != '0' ]; then
-        echo "WARNING: $fuzzy fuzzy strings in language $language."
-    fi
-
-    if [ $empty != '0' ]; then
-        echo "WARNING: $empty empty strings in language $language."
-    fi
-
-    echo "$language: [enter] to edit, [c] to continue"
-    read validatesure
-    if [[ $validatesure != 'c' ]]; then
-        $EDITOR $popath
-    fi
-    msgfmt -o $podir/$project.mo $popath
-done
+#sed '1,+17d' ./messages.pot > ./messages.pot.tmp
+#
+#pot='# '$projectc' pot file.
+## Copyright © 2013, Kwpolska.
+## This file is distributed under the same license as the '$projectc' package.
+## Kwpolska <kwpolska@kwpolska.tk>, 2013.
+##
+#msgid ""
+#msgstr ""
+#"Project-Id-Version: #version\\n"
+#"Report-Msgid-Bugs-To: Kwpolska <kwpolska@kwpolska.tk>\\n"
+#"POT-Creation-Date: #datel\\n"
+#"PO-Revision-Date: #datel\\n"
+#"Last-Translator: Kwpolska <kwpolska@kwpolska.tk>\\n"
+#"Language-Team: Kwpolska <kwpolska@kwpolska.tk>\\n"
+#"Language: en\\n"
+#"MIME-Version: 1.0\\n"
+#"Content-Type: text/plain; charset=UTF-8\\n"
+#"Content-Transfer-Encoding: 8bit\\n"'
+#
+#echo $pot > messages.pot
+#cat ./messages.pot.tmp >> messages.pot
+#rm ./messages.pot.tmp
+#
+#sed "s/#version/$version/g" messages.pot -i
+#sed "s/#datel/$datel/g" messages.pot -i
+#
+#for i in ./locale/*; do
+#    language=$(basename $i)
+#
+#    podir="./locale/$language/LC_MESSAGES"
+#    popath="./locale/$language/LC_MESSAGES/$project.po"
+#    sed 's/\"Project-Id-Version: .*/\"Project-Id-Version: '$version'\\n\"/' $popath -i
+#    msgmerge $popath messages.pot -o $popath
+#    fuzzy=$(cat $popath | grep -c '#, fuzzy')
+#    empty=$(cat $popath | pcregrep -cM 'msgstr ""\n$')
+#    if [ $fuzzy != '0' ]; then
+#        echo "WARNING: $fuzzy fuzzy strings in language $language."
+#    fi
+#
+#    if [ $empty != '0' ]; then
+#        echo "WARNING: $empty empty strings in language $language."
+#    fi
+#
+#    echo "$language: [enter] to edit, [c] to continue"
+#    read validatesure
+#    if [[ $validatesure != 'c' ]]; then
+#        $EDITOR $popath
+#    fi
+#    msgfmt -o $podir/$project.mo $popath
+#done
 
 ###: Testing and building
-python -c "import $project; import $project.ui.main"
+python -c "import $project"
 if [[ $? = 1 ]]; then
     echo "Import failed.  Fix your code or don't come back."
     exit 1
 fi
 
-#./tests.py
-#if [[ $? = 1 ]]; then
-    #echo "Tests failed.  Fix your code or don't come back."
-    #exit 1
-#fi
+./tests.py
+if [[ $? = 1 ]]; then
+    echo "Tests failed.  Fix your code or don't come back."
+    exit 1
+fi
 
 echo 'This is the last chance to quit.  Hit ^C now if you want to.'
 read bailout
@@ -148,7 +149,7 @@ else
     cm='t'
 fi
 
-rm -rf $project.egg-info __pycache__ $project/__pycache__ dist build
+rm -rf $project.egg-info __pycache__ $project/__pycache__ $project/ui/__pycache__ dist build
 
 git add *
 if [[ $? != '0' ]]; then
