Releasing soon!
Signed-off-by: Kwpolska <kwpolska@gmail.com>

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,7 +1,6 @@
 #!/bin/zsh
 project="aurqt"
 projectc="aurqt"
-aurcat="system"
 
 version=$1
 if [[ $version = '' ]]; then
@@ -10,7 +9,7 @@ if [[ $version = '' ]]; then
     read version
 fi
 
-rm -rf $project.egg-info __pycache__ $project/__pycache__ $project/ui/__pycache__ dist build
+rm -rf $project.egg-info __pycache__ $project/__pycache__ dist build
 
 date=$(date '+%Y-%m-%d')
 datel=$(date '+%Y-%m-%d %H:%M%z')
@@ -20,28 +19,27 @@ sed "s/version=.*/version='$version',/g" setup.py -i
 sed "s/release = .*/release = '$version'/g" docs/conf.py -i
 sed "s/:Version: .*/:Version: $version/g" docs/*.rst -i
 sed "s/# $projectc v.*/# $projectc v$version/" $project/*.py -i
-sed "s/# $projectc v.*/# $projectc v$version/" $project/ui/*.py -i
 sed "s/__version__ = .*/__version__ = '$version'/g" $project/__init__.py -i
 sed "s/pkgver=.*/pkgver=$version/g" PKGBUILD -i
-
 sed "s/pkgver=.*/pkgver=$datep/g" PKGBUILD-git -i
 sed "s/:Date: .*/:Date: $date/g" docs/*.rst -i
+
+###: python2-$project{,-git} packages
+#sed "s/pkgver=.*/pkgver=$version/g" PKGBUILD-2 -i
+#sed "s/pkgver=.*/pkgver=$datep/g" PKGBUILD-2-git -i
 
 cp docs/README.rst docs/CHANGELOG.rst docs/CONTRIBUTING.rst .
 cp docs/README.rst README
 
-rm docs/$project.8.gz | true
-rst2man docs/$project.rst > docs/$project.8
-gzip docs/$project.8
-
+###: Locale Generation
 xgettext -c ./$project/*.py ./$project/ui/*.py -o ./messages.pot
 
 sed '1,+17d' ./messages.pot > ./messages.pot.tmp
 
 pot='# '$projectc' pot file.
-# Copyright (C) 2011-2012, Kwpolska.
+# Copyright © 2012-2013, Kwpolska.
 # This file is distributed under the same license as the '$projectc' package.
-# Kwpolska <kwpolska@kwpolska.tk>, 2012.
+# Kwpolska <kwpolska@kwpolska.tk>, 2012-2013.
 #
 msgid ""
 msgstr ""
@@ -88,32 +86,57 @@ for i in ./locale/*; do
     msgfmt -o $podir/$project.mo $popath
 done
 
-python -c "import $project, $project.ui.main"
+###: Testing and building
+python -c "import $project; import $project.ui.main"
 if [[ $? = 1 ]]; then
     echo "Import failed.  Fix your code or don't come back."
     exit 1
 fi
+
+#./tests.py
+#if [[ $? = 1 ]]; then
+    #echo "Tests failed.  Fix your code or don't come back."
+    #exit 1
+#fi
 
 echo 'This is the last chance to quit.  Hit ^C now if you want to.'
 read bailout
 
 ./setup.py sdist upload
 
+###: AUR Package Creation
 md5out=$(md5sum 'dist/'$project'-'$version'.tar.gz'|awk '{print $1}')
 sed "s/md5sums=.*/md5sums=('$md5out')/" PKGBUILD -i
+###: python2-$project package
+#sed "s/md5sums=.*/md5sums=('$md5out')/" PKGBUILD-2 -i
+
 rm -rf MKPKGBUILD
-mkdir -p MKPKGBUILD/$project MKPKGBUILD/$project"-git"
-cp PKGBUILD MKPKGBUILD/$project
-cp PKGBUILD-git MKPKGBUILD/$project"-git/PKGBUILD"
+mkdir MKPKGBUILD
 cd MKPKGBUILD
+
+###: $project{,-git} packages
+mkdir $project{,-git}
+cp ../PKGBUILD ./$project
+cp ../PKGBUILD-git ./$project"-git/PKGBUILD"
 tar -czvf $project.src.tar.gz $project
 tar -czvf $project"-git".src.tar.gz $project"-git"
-burp -u Kwpolska -c system $project.src.tar.gz $project"-git".src.tar.gz
 
+###: python{2,}-$project{,-git} packages
+#mkdir python{,2}'-'$project{,-git}
+#cp ../PKGBUILD ./python-$project
+#cp ../PKGBUILD-git ./python-$project"-git/PKGBUILD"
+#cp ../PKGBUILD-2 ./python2-$project/PKGBUILD
+#cp ../PKGBUILD-2-git ./python2-$project"-git/PKGBUILD"
+#tar -czvf python-$project.src.tar.gz python-$project
+#tar -czvf python2-$project.src.tar.gz python-$project
+#tar -czvf python-$project"-git".src.tar.gz python-$project"-git"
+#tar -czvf python2-$project"-git".src.tar.gz python-$project"-git"
 
+aurploader -a *.src.tar.gz
 cd ..
 rm -rf MKPKGBUILD
 
+###: git commit
 if [[ $2 != '-c' ]]; then
     echo 'Commit message (sans the version?)'
     echo -n '> '
@@ -125,7 +148,7 @@ else
     cm='t'
 fi
 
-rm -rf $project.egg-info __pycache__ $project/__pycache__ $project/ui/__pycache__ dist build
+rm -rf $project.egg-info __pycache__ $project/__pycache__ dist build
 
 git add *
 if [[ $? != '0' ]]; then
